version: '3.8'
services:
  flask-app:
    # image: rickyurvina/api-qa-flask
    image: cruzroja.azurecr.io/api-qa-flask
    restart: always
    ports:
      - 5000:5000
    networks:
      - flask
networks:
    flask:
        driver: bridge